name: 'Opinionated-commit-message'
description: 'Check commit messages according to an opinionated style'
author: 'Marko Ristin'
runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'check'
  color: 'blue'
inputs:
  additional-verbs:
    description: 'Additional verbs in imperative mood to be accepted in checks'
    required: false
    default: ''
