name: 'Opinionated-commit-message'
description: 'Check commit messages according to an opinionated style'
author: 'Marko Ristin'
runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'check'
  color: 'blue'
inputs:
  additional-verbs:
    description: 'Additional verbs in imperative mood to be accepted in checks'
    required: false
    default: ''
  path-to-additional-verbs:
    description: 'Path to the file containing the additional verbs in imperative mood to be accepted in checks'
    required: false
    default: ''
  allow-one-liners:
    description: 'If set to "true", allows one-liner commit messages without body'
    required: false
    default: ''
  max-subject-line-length:
    description: 'Maximum length of the commit subject line'
    required: false
    default: ''
  min-body-length:
    description: 'Minimum length of the body of the commit message'
    required: false
    default: ''
  max-body-line-length:
    description: 'Maximum length of a line in the body of the commit message'
    required: false
    default: ''
  enforce-sign-off:
    description: 'If set to "true", signed-off-by is required in the commit message body'
    required: false
    default: ''
  skip-body-check:
    description: 'If set to "true", skip the body check'
    required: false
    default: ''
  validate-pull-request-commits:
    description: 'If set to "true", validate commits in pull requests instead of the pull request body'
    required: false
    default: ''
  ignore-merge-commits:
    description: 'If set to "false", merge commits will not be ignored.'
    required: false
    default: 'true'
  ignore-patterns:
    description: >-
      Pattern to ignore in commit messages. One pattern per line.
      Patterns are matched against the whole commit message as regular expressions without any flags.
    required: false
    default: ''
  github-token:
    description: 'GitHub token'
    required: false
    default: ''
