name: 'Opinionated-commit-message'
description: 'Check commit messages according to an opinionated style'
author: 'Marko Ristin'
runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'check'
  color: 'blue'
inputs:
  additional-verbs:
    description: 'Additional verbs in imperative mood to be accepted in checks'
    required: false
    default: ''
  path-to-additional-verbs:
    description: 'Path to the file containing the additional verbs in imperative mood to be accepted in checks'
    required: false
    default: ''
  allow-one-liners:
    description: 'If set to "true", allows one-liner commit messages without body'
    required: false
    default: ''
  enforce-sign-off:
    description: 'If set to "true", signed-off-by is required in the commit message body'
    required: false
    default: ''
