name: "build-and-test"
on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - check-all-commits

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Execute all scripts
        run: npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          additional-verbs: 'chrusimusi, unit-test'
          path-to-additional-verbs: src/additional-verbs.txt

#  test-pr-commits:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./
#        with:
#          validate-pull-request-commits: true
#          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-allow-one-liners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          allow-one-liners: 'true'
